import Head from "next/head";
import styles from "@styles/Home.module.css";
import Card from "@components/Card";
export default function Home() {
	let array = ["My name is mateo", "My name is Jeff", "Pizza is cool"];

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Example of mapping arrays and passing props to components */}
			{array.map((arr) => (
				<Card first={arr}></Card>
			))}
		</div>
	);
}
